### PR TITLE
Thu Than - Bio - PCW Session 3

### PR DESCRIPTION
**Pull request by thuinanutshell**
This is my bio description for pre-class work session 3.

### CODE REVIEW

**Comment by haechan01** [comment]
the file is empty right now

**Review by syang0624 — COMMENTED** [review]
I love how you are being mysterious but I think you might want to share at least a bit of you to us!

**Comment by Ajodo-Godson** [comment]
Empty file. 
You should probably update the file

**Review by Ajodo-Godson — COMMENTED** [review]
This is looking good.
Nice work!

**Pull request merged**
