### PR TITLE
session 3 pcw-muw

### PR DESCRIPTION
**Pull request by MacBeth-M**
whimsical biography of macbeth matibe. Pcw-muw session 3.

### CODE REVIEW

**Comment by philip-sterne** [comment]
My mochaccino formula is:

1. Mug full of full cream milk
2. Microwave for 60-90 seconds (hot, but not so hot that a milk skin forms)
3. 1 spoon of pure cocoa
4. 2 spoons of instant coffee
5. 3 spoons of sugar
6. Mix a lot, unfortunately the cocoa takes a while to get stirred in.

I'm probably overdoing the sugar, but it's delicious!

**Review by philip-sterne — APPROVED** [review]
This PR looks good. Please go ahead and merge! (I will approve the MUW once this is merged)

**Comment by MacBeth-M** [comment]
Do I need to delete this branch after merging?

**Comment by philip-sterne** [comment]
It does keep things neater if you delete branches that you won't use again. (I have gone and deleted the branch for you)

**Comment by philip-sterne** [comment]
(Ah nevermind about deleting the branch - you have forked the repo, and so the branch is not in the main repo anyway.)

**Pull request merged**
