### PR TITLE
krithik-ravindran

### PR DESCRIPTION
**Pull request by krithikravi**
Session 3 CS162 Preclass work-Markdown file with short biography

### CODE REVIEW

**Comment by Adakole2020** [comment]
Should update the commit message for better contextualization. Further, commit messages might conflict with the present one and might be problematic for later referencing. A simple amend should suffice.

**Review by Adakole2020 — APPROVED** [review]

**Comment by Adakole2020** [comment]
LGTM

**Review by Adakole2020 — COMMENTED** [review]
I believe you may need to update your file naming here to meet the file naming conventions.

**Comment by Adakole2020** [comment]
It would be better to revert and update.

**Comment by krithikravi** [comment]
Not too sure how to revert, hasn't it already been merged?

**Comment by krithikravi** [comment]
> 

nvm, just figured it out, i'll change it

**Comment by Adakole2020** [comment]
Yeah, I think it'll be a good idea to create a new MR on the new one.

**Pull request merged**
