### PR TITLE
Create Enkhjin-Gankhuyag.md

### PR DESCRIPTION
**Pull request by EnkhjinicoZSC**
Testing out pulling

### CODE REVIEW

**Review by chiragjes — CHANGES_REQUESTED** [review]
Almost everything is done well, except there needed to be lists and more formating.

**Comment by chloerobillard** [comment]
Everything looks great except more formatting could make the file even nicer. The file is in the right place.

**Review by Dilnazzzz — APPROVED** [review]
:shipit:

One suggestion is to use a variety of syntax for markdowns, including italic, quote, and bold.

**Review by Dilnazzzz — APPROVED** [review]
shipit

**Review by EnkhjinicoZSC — COMMENTED** [review]
Updated

**Review by chiragjes — APPROVED** [review]
Looks good to me!

**Pull request merged**
