### PR TITLE
Delete César-Castro.md

### PR DESCRIPTION
**Pull request by cesar-ca**

### CODE REVIEW

**Review by philip-sterne — CHANGES_REQUESTED** [review]
Please move this file, rather than delete it!

**Review by svitlanamidianko — APPROVED** [review]
yahoo

**Review by AustinPerzben — APPROVED** [review]
LGTM

**Review by philip-sterne — CHANGES_REQUESTED** [review]
Ah, I see that the file already exists in the target directory.

Please delete both files in the root directory!

**Review by akmarzhan1 — APPROVED** [review]
yay

**Pull request closed without merging**
